### ISSUE TITLE
Need to add missing Manual Test Cases in xlsx file

### ISSUE THREAD

**Issue by rkpareek** [LoginRadius/idx-auto-tester#19]
The xlsx file on the root of the project is containing all the related Test Cases. Need to add the missing Test Cases

**Comment by kritikash18** [comment]
@rkpareek Can I take this issue?

**Comment by rkpareek** [comment]
> @rkpareek Can I take this issue?

Assigned to you

**Comment by kritikash18** [comment]
@rkpareek Raised a PR
Fixed by #26
