### ISSUE TITLE
Add Github Issue Form and PR Template

### ISSUE THREAD

**Issue by Hard-Coder05** [LoginRadius/idx-auto-tester#27]
__Is your feature request related to a problem? Please describe.__

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Along with the Issue Form I would also like to add the PR themplate.

__Describe the solution you'd like__

This repository currently uses neither issue template nor PR template. Your task is to create GitHub issue form and PR template for this repository. We can use standard templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
@rkpareek I would like to work on this issue!

**Comment by Hard-Coder05** [comment]
@rkpareek I have completed the task! Please let me know if any change is needed!

**Comment by rkpareek** [comment]
@Hard-Coder05 Thanks, It's under Review
